### 根据 ID 获取用户信息
GRPC localhost:5001/user.usersvc/GetUserById

{
  "id": 2
}

### 检查手机号是否已注册
GRPC localhost:5001/user.usersvc/GetUserByMobile

{
    "phone": "16936705661"
}

### 生成图形验证码
GRPC localhost:5001/user.usersvc/SendImageCaptcha

### 验证图形验证码
GRPC localhost:5001/user.usersvc/VerifyCaptcha

{
    "captchaId": "captcha_skip_test",
    "captchaImage": "123456"
}

### 发送短信验证码
GRPC localhost:5001/user.usersvc/SendSmsCode

# 000 开头的为测试手机号, 对应的验证码为 123456
{
    "phone": "00021039435"
}

### 验证短信验证码
GRPC localhost:5001/user.usersvc/VerifySmsCode

{
    "phone": "00021039435",
    "smsCode": "123456"
}

### 注册用户
GRPC localhost:5001/user.usersvc/Register

{
  "name": "test2183",
  "email": "",
  "phone": "00021039414",
  "password": "123456",
  "city": "苏州",
  "introduction": "this is a test user",
  "avatar": "http://img-shanghai.huayuanji.com/uploads/2022/04/15/aff67eb4653e3c077bc4418fdb4af393.jpg"
}

### 登录
GRPC localhost:5001/user.usersvc/LoginByPhone

{
  "phone": "00021039410",
  "password": "123456"
}

### 刷新token
GRPC localhost:5001/user.usersvc/RefreshToken

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTIiLCJ1c2VyX25hbWUiOiIiLCJleHBpcmVfdGltZSI6MTY4MTg4MDQ1MSwiaXNzIjoidXNlcnN2Yy5ycGMiLCJleHAiOjE2ODE4ODA0NTEsIm5iZiI6MTY3NjY5NjQ1MSwiaWF0IjoxNjc2Njk2NDUxfQ.MmzNEx4dwixKhqR-YqPs1yCaW38Lhah2mpHXtKPQlBg"
}

### 获取用户列表
GRPC localhost:5001/user.usersvc/GetUserList

{
  "page": 1,
  "pageSize": 2,
  "sort": "id",
  "order": "desc"
}

### 更新用户信息
GRPC localhost:5001/user.usersvc/UpdateUser

{
  "id": 10,
  "name": "张三",
  "city": "江苏省苏州市",
  "introduction": "this is a test user introduction",
  "avatar": "http://img-shanghai.huayuanji.com/uploads/2022/04/15/aff67eb4653e3c077bc4418fdb4af393.jpg"
}










