version: "3.7"
services:
  # 数据库服务
  kong-database:
    image: postgres:12
    container_name: kong-database
    ports:
      - "5432:5432"
    environment:
      # 访问数据库的用户
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    networks:
      - kong-net
    volumes:
      # 数据库持久化目录
      - ./data/postgresql/postgresql:/var/lib/postgresql/data
  kong-gateway:
    # 镜像版本，目前最新
    image: kong/kong-gateway:3.1.1.3-alpine
    container_name: kong-gateway
    environment:
      # 数据持久化方式，使用postgres数据库
      - "KONG_DATABASE=postgres"
      # 数据库容器名称,Kong连接数据时使用些名称
      - "KONG_PG_HOST=kong-database"
      - "KONG_PG_USER=kong"
      - "KONG_PG_PASSWORD=kongpass"
      # 数据库名称
      - "KONG_CASSANDRA_CONTACT_POINTS=kong-database"
      # 日志记录目录
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      # 暴露的端口
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"
      - "KONG_ADMIN_GUI_URL=http://localhost:8002"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    # 使用docker网络
    networks:
      - kong-net
    # 依赖数据库服务
    depends_on:
      - kong-database
  # kong 管理界面
  konga:
    #    image: pantsel/konga  # for intel
    image: mstinebaugh/konga  # for mac m1
    container_name: konga
    environment:
#      - "TOKEN_SECRET=51liveup.cn"
      # 初始化使用development， 去初始化数据表， 正式使用production
      - "NODE_ENV=development"
      - "DB_ADAPTER=postgres"
      - "DB_HOST=kong-database"
      - "DB_PORT=5432"
      - "DB_USER=kong"
      - "DB_PASSWORD=kongpass"
      - "DB_DATABASE=konga-db"
    ports:
      - "18080:1337"
    networks:
      - kong-net
    depends_on:
      - kong-database
networks:
  kong-net:
    external: true
