// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheMsUserLikesIdPrefix = "cache:msUser:likes:id:"
)

type (
	likesModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Likes) error

		FindOne(ctx context.Context, id int64) (*Likes, error)
		Update(ctx context.Context, tx *gorm.DB, data *Likes) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultLikesModel struct {
		gormc.CachedConn
		table string
	}

	Likes struct {
		Id        int64          `gorm:"column:id"`
		Name      string         `gorm:"column:name"`
		Email     sql.NullString `gorm:"column:email"`
		Phone     sql.NullString `gorm:"column:phone"`
		Password  sql.NullString `gorm:"column:password"`
		CreatedAt sql.NullTime   `gorm:"column:created_at"`
		UpdatedAt sql.NullTime   `gorm:"column:updated_at"`
	}
)

func (Likes) TableName() string {
	return "`likes`"
}

func newLikesModel(conn *gorm.DB, c cache.CacheConf) *defaultLikesModel {
	return &defaultLikesModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`likes`",
	}
}

func (m *defaultLikesModel) Insert(ctx context.Context, tx *gorm.DB, data *Likes) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultLikesModel) FindOne(ctx context.Context, id int64) (*Likes, error) {
	msUserLikesIdKey := fmt.Sprintf("%s%v", cacheMsUserLikesIdPrefix, id)
	var resp Likes
	err := m.QueryCtx(ctx, &resp, msUserLikesIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Likes{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikesModel) Update(ctx context.Context, tx *gorm.DB, data *Likes) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultLikesModel) getCacheKeys(data *Likes) []string {
	if data == nil {
		return []string{}
	}
	msUserLikesIdKey := fmt.Sprintf("%s%v", cacheMsUserLikesIdPrefix, data.Id)
	cacheKeys := []string{
		msUserLikesIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultLikesModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Likes{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultLikesModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultLikesModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMsUserLikesIdPrefix, primary)
}

func (m *defaultLikesModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Likes{}).Where("`id` = ?", primary).Take(v).Error
}
