// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheMsUserLinksIdPrefix = "cache:msUser:links:id:"
)

type (
	linksModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Links) error

		FindOne(ctx context.Context, id int64) (*Links, error)
		Update(ctx context.Context, tx *gorm.DB, data *Links) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultLinksModel struct {
		gormc.CachedConn
		table string
	}

	Links struct {
		Id        int64          `gorm:"column:id"`
		Name      string         `gorm:"column:name"`
		Url       sql.NullString `gorm:"column:url"`
		CreatedAt sql.NullTime   `gorm:"column:created_at"`
		UpdatedAt sql.NullTime   `gorm:"column:updated_at"`
	}
)

func (Links) TableName() string {
	return "`links`"
}

func newLinksModel(conn *gorm.DB, c cache.CacheConf) *defaultLinksModel {
	return &defaultLinksModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`links`",
	}
}

func (m *defaultLinksModel) Insert(ctx context.Context, tx *gorm.DB, data *Links) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultLinksModel) FindOne(ctx context.Context, id int64) (*Links, error) {
	msUserLinksIdKey := fmt.Sprintf("%s%v", cacheMsUserLinksIdPrefix, id)
	var resp Links
	err := m.QueryCtx(ctx, &resp, msUserLinksIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Links{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLinksModel) Update(ctx context.Context, tx *gorm.DB, data *Links) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultLinksModel) getCacheKeys(data *Links) []string {
	if data == nil {
		return []string{}
	}
	msUserLinksIdKey := fmt.Sprintf("%s%v", cacheMsUserLinksIdPrefix, data.Id)
	cacheKeys := []string{
		msUserLinksIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultLinksModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Links{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultLinksModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultLinksModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMsUserLinksIdPrefix, primary)
}

func (m *defaultLinksModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Links{}).Where("`id` = ?", primary).Take(v).Error
}
