// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheMsUserMigrationsIdPrefix        = "cache:msUser:migrations:id:"
	cacheMsUserMigrationsMigrationPrefix = "cache:msUser:migrations:migration:"
)

type (
	migrationsModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Migrations) error

		FindOne(ctx context.Context, id int64) (*Migrations, error)
		FindOneByMigration(ctx context.Context, migration string) (*Migrations, error)
		Update(ctx context.Context, tx *gorm.DB, data *Migrations) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultMigrationsModel struct {
		gormc.CachedConn
		table string
	}

	Migrations struct {
		Id        int64         `gorm:"column:id"`
		Migration string        `gorm:"column:migration"`
		Batch     sql.NullInt64 `gorm:"column:batch"`
	}
)

func (Migrations) TableName() string {
	return "`migrations`"
}

func newMigrationsModel(conn *gorm.DB, c cache.CacheConf) *defaultMigrationsModel {
	return &defaultMigrationsModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`migrations`",
	}
}

func (m *defaultMigrationsModel) Insert(ctx context.Context, tx *gorm.DB, data *Migrations) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultMigrationsModel) FindOne(ctx context.Context, id int64) (*Migrations, error) {
	msUserMigrationsIdKey := fmt.Sprintf("%s%v", cacheMsUserMigrationsIdPrefix, id)
	var resp Migrations
	err := m.QueryCtx(ctx, &resp, msUserMigrationsIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Migrations{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMigrationsModel) FindOneByMigration(ctx context.Context, migration string) (*Migrations, error) {
	msUserMigrationsMigrationKey := fmt.Sprintf("%s%v", cacheMsUserMigrationsMigrationPrefix, migration)
	var resp Migrations
	err := m.QueryRowIndexCtx(ctx, &resp, msUserMigrationsMigrationKey, m.formatPrimary, func(conn *gorm.DB, v interface{}) (interface{}, error) {
		if err := conn.Model(&Migrations{}).Where("`migration` = ?", migration).Take(&resp).Error; err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMigrationsModel) Update(ctx context.Context, tx *gorm.DB, data *Migrations) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultMigrationsModel) getCacheKeys(data *Migrations) []string {
	if data == nil {
		return []string{}
	}
	msUserMigrationsIdKey := fmt.Sprintf("%s%v", cacheMsUserMigrationsIdPrefix, data.Id)
	msUserMigrationsMigrationKey := fmt.Sprintf("%s%v", cacheMsUserMigrationsMigrationPrefix, data.Migration)
	cacheKeys := []string{
		msUserMigrationsIdKey, msUserMigrationsMigrationKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultMigrationsModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Migrations{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultMigrationsModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultMigrationsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMsUserMigrationsIdPrefix, primary)
}

func (m *defaultMigrationsModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Migrations{}).Where("`id` = ?", primary).Take(v).Error
}
