// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheMsUserTopicsIdPrefix = "cache:msUser:topics:id:"
)

type (
	topicsModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Topics) error

		FindOne(ctx context.Context, id int64) (*Topics, error)
		Update(ctx context.Context, tx *gorm.DB, data *Topics) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultTopicsModel struct {
		gormc.CachedConn
		table string
	}

	Topics struct {
		Id         int64        `gorm:"column:id"`
		Title      string       `gorm:"column:title"`
		Body       string       `gorm:"column:body"`
		UserId     int64        `gorm:"column:user_id"`
		CategoryId int64        `gorm:"column:category_id"`
		CreatedAt  sql.NullTime `gorm:"column:created_at"`
		UpdatedAt  sql.NullTime `gorm:"column:updated_at"`
	}
)

func (Topics) TableName() string {
	return "`topics`"
}

func newTopicsModel(conn *gorm.DB, c cache.CacheConf) *defaultTopicsModel {
	return &defaultTopicsModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`topics`",
	}
}

func (m *defaultTopicsModel) Insert(ctx context.Context, tx *gorm.DB, data *Topics) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultTopicsModel) FindOne(ctx context.Context, id int64) (*Topics, error) {
	msUserTopicsIdKey := fmt.Sprintf("%s%v", cacheMsUserTopicsIdPrefix, id)
	var resp Topics
	err := m.QueryCtx(ctx, &resp, msUserTopicsIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Topics{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTopicsModel) Update(ctx context.Context, tx *gorm.DB, data *Topics) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultTopicsModel) getCacheKeys(data *Topics) []string {
	if data == nil {
		return []string{}
	}
	msUserTopicsIdKey := fmt.Sprintf("%s%v", cacheMsUserTopicsIdPrefix, data.Id)
	cacheKeys := []string{
		msUserTopicsIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultTopicsModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Topics{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultTopicsModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultTopicsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMsUserTopicsIdPrefix, primary)
}

func (m *defaultTopicsModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Topics{}).Where("`id` = ?", primary).Take(v).Error
}
