### Ping
POST {{userapi}}/users/ping
Content-Type: application/json

### User register
POST {{userapi}}/users/update
Content-Type: application/json

{
  "id": 1,
  "nickName": "RibonUpdate"
}

### Delete user
DELETE {{userapi}}/users/1
Content-Type: application/json