// Code generated by goctl. DO NOT EDIT.
package types

type PhoneExistReq struct {
	Phone string `json:"phone" validate:"required,len=11"`
}

type PhoneExistReply struct {
	Exist bool `json:"exist"`
}

type CaptchaReply struct {
	CaptchaId    string `json:"captchaId"`
	CaptchaImage string `json:"captchaImage"`
}
