air := $(shell which air)
sql2pb := $(shell which sql2pb)
goctl := $(shell which goctl)
dir = ~/code/go/go-zero/MiddleStage

gen-model:
	@$(goctl) model mysql datasource -url="root:PXDN93VRKUm8TeE7@tcp(localhost:3310)/ms_user" -table="$(m)"  -dir="rpc/model" -cache=true --style=goZero --home ../../tpl





